name: Update Random Programming Quote

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6am UTC
  push:
    paths:
      - 'random-quote.js'
      - 'README.md'

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Run random quote script
        run: node random-quote.js
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update random programming quote [bot]' || echo 'No changes to commit'
          git push 